//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.24 at 03:13:28 PM CEST 
//


package fr.treeptik.blog.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="comId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="comNom" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="comEmail" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="comText" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="comDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="comValidation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Articles" type="{http://www.w3schools.com}Articles"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "comId",
    "comNom",
    "comEmail",
    "comText",
    "comDate",
    "comValidation",
    "articles"
})
@XmlRootElement(name = "commentaires")
public class Commentaires {

    protected int comId;
    @XmlElement(required = true)
    protected String comNom;
    @XmlElement(required = true)
    protected String comEmail;
    @XmlElement(required = true)
    protected String comText;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar comDate;
    @XmlElement(required = true)
    protected String comValidation;
    @XmlElement(name = "Articles", required = true)
    protected Articles articles;

    /**
     * Gets the value of the comId property.
     * 
     */
    public int getComId() {
        return comId;
    }

    /**
     * Sets the value of the comId property.
     * 
     */
    public void setComId(int value) {
        this.comId = value;
    }

    /**
     * Gets the value of the comNom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComNom() {
        return comNom;
    }

    /**
     * Sets the value of the comNom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComNom(String value) {
        this.comNom = value;
    }

    /**
     * Gets the value of the comEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComEmail() {
        return comEmail;
    }

    /**
     * Sets the value of the comEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComEmail(String value) {
        this.comEmail = value;
    }

    /**
     * Gets the value of the comText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComText() {
        return comText;
    }

    /**
     * Sets the value of the comText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComText(String value) {
        this.comText = value;
    }

    /**
     * Gets the value of the comDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getComDate() {
        return comDate;
    }

    /**
     * Sets the value of the comDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setComDate(XMLGregorianCalendar value) {
        this.comDate = value;
    }

    /**
     * Gets the value of the comValidation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComValidation() {
        return comValidation;
    }

    /**
     * Sets the value of the comValidation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComValidation(String value) {
        this.comValidation = value;
    }

    /**
     * Gets the value of the articles property.
     * 
     * @return
     *     possible object is
     *     {@link Articles }
     *     
     */
    public Articles getArticles() {
        return articles;
    }

    /**
     * Sets the value of the articles property.
     * 
     * @param value
     *     allowed object is
     *     {@link Articles }
     *     
     */
    public void setArticles(Articles value) {
        this.articles = value;
    }

}
